### PR TITLE
Add unit tests

### PR DESCRIPTION
**Pull request by bstienen**
Unit tests are added for the entire package, providing full coverage for the code as it currently is. This answers issue #5. Additionally a location for implementations has been added in the form of two submodules: posterior and optimisation.

### CODE REVIEW

**Comment by williamjameshandley** [comment]
This is an extremely impressive and worthwhile addition @bstienen. Well done for all this hard work!

It's probably a good idea to avoid `# pragma: nocover` statements. Whilst 100% coverage is an admirable goal, getting there by dropping lines of code doesn't abide by the spirit of such things.

For future pull requests, it might be good to enforce at least one code review before merging into master (you can do this by changing the settings).

Now that we have a full test suite, you can probably introduce automatic checks via the CI into pull requests.

**Comment by bstienen** [comment]
Thanks for your comment @williamjameshandley! I will create a pull request later today removing the #pragma statements. They were added initially to avoid the following problems:

- Opening a matplotlib window through .show() requires user input in the form of closing the window in order for the program to continue. Testing that .show() works properly would, if I am correct, stop the unit test, right?
- There are a couple of abstract classes with abstract methods, which cannot be called directly. See for example procedures.Procedure. There are lines that cannot be run, as any class derived from these needs to implement the abstract methods themselves.

On the other hand i see why my pragma-comments are considered bad practice. But don't get me wrong, if you know a way to avoid these problems, please let me know!

I am not sure if i get your last comment about automatic checks via CI. When I create a pull request, the code of the request gets checked by Travis already. Is this what you mean?

**Comment by williamjameshandley** [comment]
>I am not sure if i get your last comment about automatic checks via CI. When I create a pull request, the code of the request gets checked by Travis already. Is this what you mean?

I have configured the branch protection rules for the repository such that

a) At least one code review is required before merging
b) The travis tests have to pass in order to merge

You can revert these changes by visiting the [branch protection rules](https://github.com/DarkMachines/high-dimensional-sampling/settings/branch_protection_rules/6468350) in the repository settings

**Comment by bstienen** [comment]
Aaaaah thats what you meant. Now I get it :-) I see it in the settings now. Seems like a good policy, so lets keep it in place.

**Pull request merged**
