### PR TITLE
TuRBO interface

### PR DESCRIPTION
**Pull request by EduardoGarrido90**
THIS PULL REQUEST SUBSTITUTES THE PREVIOUS ONE THAT HAD SO MANY FILES.

It seems that, on the last version of HDS, my TuRBO interface was able to solve all the problems without modifying HDS. Here I leave you with the file. 

Default parameters may be varied in order for the algorithm to work better. 

Best,
Eduardo.

### CODE REVIEW

**Comment by bstienen** [comment]
I would like to test your code and implement your Procedure in the package itself, but to do that, I need to know what the dependencies of this script are. I tried googling for `Turbo`, but could not find anything that looked like a sampler. Can you give the URL of the dependency?

**Comment by EduardoGarrido90** [comment]
> I would like to test your code and implement your Procedure in the package itself, but to do that, I need to know what the dependencies of this script are. I tried googling for `Turbo`, but could not find anything that looked like a sampler. Can you give the URL of the dependency?

Dear Bob,

Thanks for reviewing the interface. The URL of the package is this one: https://github.com/uber-research/TuRBO . It is enough to clone and install the packages. It has the following dependencies: numpy , pygame, box2d-py.

Please comment here any problem that may appear,

Thanks one again,

Best,

Eduardo.

**Comment by bstienen** [comment]
I installed turbo successfully, but when trying to run your example code I get the following error message in the most recent version of HDS:

    Traceback (most recent call last):
        File "turbotest.py", line 77, in <module>
            experiment.run(function, finish_line=1000) #1000
        File "/usr/local/lib/python3.7/site-packages/high_dimensional_sampling/experiments.py", line 224, in run
            self._perform_experiment(function, log_data)
        File "/usr/local/lib/python3.7/site-packages/high_dimensional_sampling/experiments.py", line 97, in _perform_experiment
            x, y = self.procedure(self.function)
        File "turbotest.py", line 55, in __call__
            turbo_m.optimize()
        File "/usr/local/lib/python3.7/site-packages/turbo/turbo_m.py", line 149, in optimize
            fX_init = np.array([[self.f(x)] for x in X_init])
        File "/usr/local/lib/python3.7/site-packages/turbo/turbo_m.py", line 149, in <listcomp>
            fX_init = np.array([[self.f(x)] for x in X_init])
        File "/usr/local/lib/python3.7/site-packages/high_dimensional_sampling/functions.py", line 70, in __call__
            self.check_dimensionality(x.shape)
        File "/usr/local/lib/python3.7/site-packages/high_dimensional_sampling/functions.py", line 125, in check_dimensionality
            dim_data = shape[1]
    IndexError: tuple index out of range

Is this, by any chance, the error that you wanted to have solved by altering the HDS package?

**Comment by EduardoGarrido90** [comment]
Yes!

I got that error I remember. Basically HDS expected an array of points and
turbo only feed it with one point.

I solve it by placing an if at that point. It was something simple when you
debug it. Not sure about if it is the best thing to do from the HDS point
of view.

After solving that bug another easy bug that happened to be something
similar appeared in other line of code.

What I do not understand is why I downloaded the last branch and that error
did not happen again to me, executing all the test programs.

Best,
Eduardo.

**Comment by bstienen** [comment]
I will have a look at this as soon as possible :-)

**Comment by EduardoGarrido90** [comment]
Thank you Bob! Hope that the code will work OK!

Un saludo,
Eduardo.

**Comment by bstienen** [comment]
I have integrated your implementation in the HDS package itself (#35). You can find it in the `optimisation` module as `TuRBO()`.

**Pull request merged**
