### PR TITLE
Need consistent cases for variable names in pyscannerbit interface + reshaping pyscannerbit output

### PR DESCRIPTION
**Pull request by ZacSpec**
At some point, cases became out of sync (diver_NP vs diver_np). Note that this is my second attempt to fix this (my git management could use some work).

### CODE REVIEW

**Comment by ZacSpec** [comment]
Also added a reshape to output of pyscannerbit, due to an error arising during logging of HiddenFunction testing. 

Error was:

```
Traceback (most recent call last):
  File "examples/pyscannerbit_hds_interface.py", line 50, in <module>
    experiment.run(function, finish_line=1000)
  File "/home/zac/anaconda3/envs/Python36/lib/python3.6/site-packages/high_dimensional_sampling/experiments.py", line 224, in run
    self._perform_experiment(function, log_data)
  File "/home/zac/anaconda3/envs/Python36/lib/python3.6/site-packages/high_dimensional_sampling/experiments.py", line 106, in _perform_experiment
    self.logger.log_samples(x, y)
  File "/home/zac/anaconda3/envs/Python36/lib/python3.6/site-packages/high_dimensional_sampling/experiments.py", line 396, in log_samples
    header += ['y' + str(i) for i in range(len(y[0]))]
TypeError: object of type 'numpy.float64' has no len()

```

**Comment by bstienen** [comment]
The output of the `HiddenFunction`s was not consistent with the rest of the package. I have fixed this in #24, so the reshape is very likely not necessary anymore. There is however no harm in having it there (although it effectively does nothing anymore). @ZacSpec do you want to remove the reshape or just leave it there?

**Comment by ZacSpec** [comment]
I'll remove it. Makes for nicer code.

**Comment by ZacSpec** [comment]
Had an issue with the inverting of the function interfering with correct reporting of sampled function values. @bstienen this interface is now working when I test it.

**Comment by bstienen** [comment]
If this work, I will merge it, but may I ask you to create an issue for the error you found with the .invert interface?

**Pull request merged**
