### PR TITLE
Added the CMA es optimisation from the CMA package.

### PR DESCRIPTION
**Pull request by gudlaugu**
Hope this is the right thing to do.  First time using github functionality.  The code requires the cma package to be installed.

### CODE REVIEW

**Comment by bstienen** [comment]
You are absolutely right that your code needs the `cma` package to be installed. To make sure the tests we run on your code works properly, could you change the following line

` tests_require=[
        'pytest',
        'pytest-cov',
        'pycodestyle'
],`

in setup.py (in the main directory of the repository) to

` tests_require=[
        'pytest',
        'pytest-cov',
        'pycodestyle',
        'cma'
],`


If you do this and commit the changes to the CMA branch in your fork, this would solve the errors that the code tests raise.

**Comment by bstienen** [comment]
Hi :-) What is the current status on this? Could you give an update?

**Comment by gudlaugu** [comment]
Sorry, did not realize I had to do this.

**Comment by bstienen** [comment]
O no problem. Since your initial commit there has been a small update to the abstract methods of the Procedure class, which makes the code you wrote break at the moment. To solve this, you have to add the following method to your CMAOptimisation class:

        def check_testfunction(self, function):
            return True

I think this will be everything that needs to be fixed, but I am not sure (as this error blocks any further testing of your code). If you give me write access to the gudlaugu:CMA branch I can make sure that all code technical errors will be handled.

**Comment by gudlaugu** [comment]
I added you as a collaborator to the clone, hope that is enough

**Comment by bstienen** [comment]
Okay, so the last error (I am sure this is the last error this time :P) I get is related to the logging of the CMA options that you store in the .opt property of your procedure class. Is it a problem if we just not store these options (like I did in the most recent commit to your repo)? As far as I can see the only thing that this object is used for in the class itself is to store the sampling ranges, which are function dependent and are therefore written to the object on each and every call of the procedure. Not storing the CMAOptions object seems to be fine in that case.

If not, we need to come up with a solution that allows us to store the CMAOptions object in .yaml format. Nothing that cannot be done, but it _is_ something we should think about then.

**Comment by gudlaugu** [comment]
I don't think it is needed unless we start varying some of the options.  In that case we can modify the class so that it only stores the options we actually vary, that is the dictionary input to the constructor.

**Comment by bstienen** [comment]
In that case let's merge it and see if the need for finer control arises at some point.

**Pull request merged**
